name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn install
      - name: check
        run: |
          cd functions
          ls
      - name: Build
        run: yarn build
      - name: check
        run: |
          cd functions
          ls
  deploy:
    name: Deploy
    needs: build
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: check
        run: |
          cd functions
          ls
      - name: Ready to deploy
        run: |
          npm install -g firebase-tools
          cd functions
          npm install
      - name: Deploy
        run: firebase deploy --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}